version: '4.4'

services:
  ollama-benchmark:
    build: .
    container_name: ollama-benchmark
    environment:
      - OLLAMA_HOST=ollama:11434
      - BENCHMARK_ITERATIONS=3
      - BENCHMARK_MODEL=gemma3:b
    volumes:
      - ./results:/app/results
    # No GPU access needed - we're using API to existing Ollama instance
    restart: no
    networks: 
    - agent_network

  # ROCm-enabled Ollama instance
  ollama-rocm:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama    
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - "44"   # video group
      - "107"  # render group
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    restart: unless-stopped
    networks: 
    - agent_network

  # Optional: CPU-only Ollama instance for comparison
  ollama-cpu:
    image: ollama/ollama:latest
    container_name: ollama-cpu-comparison
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_GPUS=0  # Force CPU-only
    ports:
      - "11435:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    networks: 
    - agent_network

volumes:
  ollama:

networks:
  agent_network:
    external: true